# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31d2b63d78d109e655d671408cdfccf516279915a217c062d06dde20bb1df92959c4c184de18e876877932c5e609fe57938a87b463aeccb75ac2210b3498aefb

test:
  secret_key_base: 7ce1e385e8e1b14ece48aabc0bc4a67bc751598ed5a9fe5e335a29b02e202e19c9e69c0d2a222294082dbcc72aebf8ca6051bff605da935f8bcad2af76218933

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
